name: HanserPyLibrary
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Locking Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        python -m pipenv lock -r -d > requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: PyLint
      run: |
        python -m pylint --rcfile .pylintrc -f colorized hanser_py_library
