name: Check
on:
  push:
    branches: 
      - master
      - v0.2.0
    tags-ignore:
      v*

jobs:
  codestyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Lock and install dependencies
      id: prep
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install -d

    - name: PyLint
      id: pylint
      run: pipenv run pylint -f colorized hanser_py_library || pylint-exit -efail -wfail $?

    - name: Flake8
      id: flake8
      run : pipenv run flake8 --exit-zero --doctests --max-doc-length 72 hanser_py_library
